### ISSUE TITLE
Select Low IF when possible?

### ISSUE THREAD

**Issue by ericek111** [ericek111/libmirisdr-5#1]
Vladisslav P. has implemented these automatic low IF selections in his fork:

https://github.com/vladisslav2011/libmirisdr-4/commit/90e1ae69e34f16bfaf9b3c038c44dc511cd9a95c
https://github.com/vladisslav2011/libmirisdr-4/commit/da32ef373a74c02488f974ed2e70b1797d28d550

Should we do the same? Or leave it to the user?

**Comment by nmaster2042** [comment]
I think automatic selection is better.

It makes usage easier.

**Comment by ericek111** [comment]
Those commits have been merged, I forgot about this issue. :D The behaviour can be disabled by calling `mirisdr_set_offset_tuning(dev, 0 for manual or 1 for automatic)`. This is also exposed in the SoapyMiri module: https://github.com/ericek111/SoapyMiri/blob/main/Settings.cpp#L351
