### ISSUE TITLE
Is this version 4 or 5?

### ISSUE THREAD

**Issue by zaninime** [ericek111/libmirisdr-5#2]
I've been using your fork for a few days, however I am not sure if this is really version 5 or if it's just a 4.x with some extra changes. While this seems a stupid question, the problem lies in the project name: very few software include the version in the name, as it makes things more difficult in the long term maintenance. Especially for package maintainers, it could easily become a nightmare.

Related to the above, are you planning to keep working on your fork in isolation or is your plan to bring back your changes [upstream](https://github.com/f4exb/libmirisdr-4)?

As a side note, thanks for taking care of this project.

**Comment by ericek111** [comment]
Sorry, I have no idea how I missed all these issue reports. I'll check my notification settings...

This is mostly backwards compatible with libmirisdr-4 and compatibility will be provided on "best effort" basis. I have already added some new functions, implemented support for Android... And most importantly, I have (conservatively) included some great improvements by vladisslav2011 -- for example, the ability to use 14 MHz of bw by bypassing the IF filter.

So this is a separate project, but you should be able to use it as a (better) replacement for libmirisdr-4. One day, I'll get around to updating the README, too.

**Comment by zaninime** [comment]
Thanks for the explanation, I see you also renamed your repo to libmirisdr-5.
